# configure auto-configured MultipartConfigElement

multipart:
  maxFileSize: 50MB
  maxRrequestSize: 50MB
  location: ${java.io.tmpdir}

spring:
  mvc:
    favicon:
      enabled: false

com:
  justgifit:
    optimize: true
    gif-location: ${java.io.tmpdir}/gif

security:
  basic:
    enabled: false